// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Socona.ImVehicle.Core.Data;
using System;

namespace Socona.ImVehicle.Core.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    partial class VehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.DistrictItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(2048);

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<int>("DivisionType");

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<int>("Status");

                    b.Property<int>("VersionNumber");

                    b.HasKey("Id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.DriverItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AvatarImageId");

                    b.Property<string>("ContactAddress")
                        .HasMaxLength(2048);

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<long?>("ExtraImage1Id");

                    b.Property<long?>("ExtraImage2Id");

                    b.Property<long?>("ExtraImage3Id");

                    b.Property<DateTime?>("FirstLicenseIssueDate");

                    b.Property<int>("Gender");

                    b.Property<long?>("GroupId");

                    b.Property<long?>("IdCardImage1Id");

                    b.Property<long?>("IdCardImage2Id");

                    b.Property<string>("IdCardNumber")
                        .HasMaxLength(128);

                    b.Property<long?>("LicenseImageId");

                    b.Property<DateTime?>("LicenseIssueDate");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(128);

                    b.Property<string>("LicenseType");

                    b.Property<int?>("LicenseValidYears");

                    b.Property<string>("LivingAddress")
                        .HasMaxLength(2048);

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<int?>("ResidentType");

                    b.Property<int>("Status");

                    b.Property<string>("Tel")
                        .HasMaxLength(128);

                    b.Property<string>("Title")
                        .HasMaxLength(32);

                    b.Property<long?>("TownId");

                    b.Property<int>("VersionNumber");

                    b.Property<string>("WarrantyCode")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("AvatarImageId");

                    b.HasIndex("ExtraImage1Id");

                    b.HasIndex("ExtraImage2Id");

                    b.HasIndex("ExtraImage3Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IdCardImage1Id");

                    b.HasIndex("IdCardImage2Id");

                    b.HasIndex("LicenseImageId");

                    b.HasIndex("TownId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.GroupItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(2048);

                    b.Property<long?>("ApplicationFileId");

                    b.Property<string>("AttachmentFilePath")
                        .HasMaxLength(2048);

                    b.Property<string>("ChiefName")
                        .HasMaxLength(32);

                    b.Property<string>("ChiefTel")
                        .HasMaxLength(64);

                    b.Property<string>("ChiefTitle")
                        .HasMaxLength(64);

                    b.Property<string>("Code")
                        .HasMaxLength(64);

                    b.Property<string>("Comment");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<long?>("DriverGuranteeFileId");

                    b.Property<long?>("ExtraImage1Id");

                    b.Property<long?>("ExtraImage2Id");

                    b.Property<long?>("ExtraImage3Id");

                    b.Property<long?>("GroupGuranteeFileId");

                    b.Property<string>("License")
                        .HasMaxLength(256);

                    b.Property<long?>("LicenseImageId");

                    b.Property<long?>("MainImageId");

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<string>("PoliceOffice")
                        .HasMaxLength(128);

                    b.Property<string>("Policeman")
                        .HasMaxLength(32);

                    b.Property<string>("RegisterAddress")
                        .HasMaxLength(2048);

                    b.Property<long?>("RuleFileId");

                    b.Property<int>("Status");

                    b.Property<long?>("TownId");

                    b.Property<string>("Type")
                        .HasMaxLength(128);

                    b.Property<int>("VersionNumber");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFileId");

                    b.HasIndex("DriverGuranteeFileId");

                    b.HasIndex("ExtraImage1Id");

                    b.HasIndex("ExtraImage2Id");

                    b.HasIndex("ExtraImage3Id");

                    b.HasIndex("GroupGuranteeFileId");

                    b.HasIndex("LicenseImageId");

                    b.HasIndex("MainImageId");

                    b.HasIndex("RuleFileId");

                    b.HasIndex("TownId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.NewsItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Area");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Excerpt");

                    b.Property<DateTime?>("ExpireDate");

                    b.Property<bool?>("HasDateRange");

                    b.Property<long?>("ImageFileId");

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<int?>("Order");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Source")
                        .HasMaxLength(256);

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("VersionNumber");

                    b.HasKey("Id");

                    b.HasIndex("ImageFileId");

                    b.ToTable("Newses");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.SecurityPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(2048);

                    b.Property<string>("Company")
                        .HasMaxLength(512);

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<long?>("GroupId");

                    b.Property<string>("IdCardNum")
                        .HasMaxLength(128);

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<string>("RegisterAddress")
                        .HasMaxLength(2048);

                    b.Property<int>("Status");

                    b.Property<string>("Tel")
                        .HasMaxLength(64);

                    b.Property<string>("Title")
                        .HasMaxLength(32);

                    b.Property<long?>("TownId");

                    b.Property<int>("VersionNumber");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TownId");

                    b.ToTable("SecurityPersons");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.TownItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(2048);

                    b.Property<int>("Code");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<long>("DirstrictId");

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<int>("Status");

                    b.Property<int>("VersionNumber");

                    b.HasKey("Id");

                    b.HasIndex("DirstrictId");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.UserFileItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientPath")
                        .HasMaxLength(2048);

                    b.Property<string>("ContentType")
                        .HasMaxLength(512);

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<int>("DownloadCount");

                    b.Property<string>("FileName")
                        .HasMaxLength(256);

                    b.Property<long?>("GroupId");

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<string>("ServerPath")
                        .HasMaxLength(2048);

                    b.Property<long>("Size");

                    b.Property<int>("Status");

                    b.Property<long?>("TownId");

                    b.Property<string>("Type")
                        .HasMaxLength(64);

                    b.Property<int>("VersionNumber");

                    b.Property<int>("Visibility");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TownId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Agent")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("AuditExpiredDate");

                    b.Property<string>("Brand")
                        .HasMaxLength(64);

                    b.Property<string>("Color")
                        .HasMaxLength(64);

                    b.Property<string>("Comment");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<long?>("DriverId");

                    b.Property<string>("DriverName")
                        .HasMaxLength(32);

                    b.Property<string>("DriverTel")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("DumpDate");

                    b.Property<long?>("ExtraImage1Id");

                    b.Property<long?>("ExtraImage2Id");

                    b.Property<long?>("ExtraImage3Id");

                    b.Property<DateTime?>("FirstRegisterDate");

                    b.Property<long?>("FrontImageId");

                    b.Property<bool?>("GpsEnabled");

                    b.Property<long?>("GpsImageId");

                    b.Property<long?>("GroupId");

                    b.Property<DateTime?>("LastRegisterDate");

                    b.Property<string>("LicenceNumber")
                        .HasMaxLength(64);

                    b.Property<long?>("LicenseImageId");

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("ProductionDate");

                    b.Property<string>("RealOwner")
                        .HasMaxLength(128);

                    b.Property<long?>("RearImageId");

                    b.Property<int>("Status");

                    b.Property<long?>("TownId");

                    b.Property<int>("Type");

                    b.Property<int>("Usage");

                    b.Property<string>("VehicleStatus")
                        .HasMaxLength(32);

                    b.Property<int>("VersionNumber");

                    b.Property<DateTime?>("YearlyAuditDate");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ExtraImage1Id");

                    b.HasIndex("ExtraImage2Id");

                    b.HasIndex("ExtraImage3Id");

                    b.HasIndex("FrontImageId");

                    b.HasIndex("GpsImageId");

                    b.HasIndex("GroupId");

                    b.HasIndex("LicenseImageId");

                    b.HasIndex("RearImageId");

                    b.HasIndex("TownId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<int>("Event");

                    b.Property<string>("IpAddr")
                        .HasMaxLength(256);

                    b.Property<string>("Metadata");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasMaxLength(512);

                    b.Property<string>("NewData");

                    b.Property<string>("OldData");

                    b.Property<int>("Status");

                    b.Property<string>("Summary")
                        .HasMaxLength(4096);

                    b.Property<string>("Url")
                        .HasMaxLength(2048);

                    b.Property<int>("VersionNumber");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseRoleId")
                        .HasMaxLength(256);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("LocalName")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<int>("Status");

                    b.Property<bool>("Visible");

                    b.HasKey("Id");

                    b.HasIndex("BaseRoleId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Company")
                        .HasMaxLength(2048);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreateBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Depart")
                        .HasMaxLength(64);

                    b.Property<long?>("DistrictId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<long?>("GroupId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<DateTime?>("ModificationDate");

                    b.Property<string>("ModifyBy")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("RealName")
                        .HasMaxLength(64);

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Serial")
                        .HasMaxLength(128);

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .HasMaxLength(64);

                    b.Property<long?>("TownId");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("Type")
                        .HasMaxLength(64);

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("GroupId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.HasIndex("TownId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.DriverItem", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "AvatarImage")
                        .WithMany()
                        .HasForeignKey("AvatarImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage1")
                        .WithMany()
                        .HasForeignKey("ExtraImage1Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage2")
                        .WithMany()
                        .HasForeignKey("ExtraImage2Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage3")
                        .WithMany()
                        .HasForeignKey("ExtraImage3Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.GroupItem", "Group")
                        .WithMany("Drivers")
                        .HasForeignKey("GroupId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "IdCardImage1")
                        .WithMany()
                        .HasForeignKey("IdCardImage1Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "IdCardImage2")
                        .WithMany()
                        .HasForeignKey("IdCardImage2Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "LicenseImage")
                        .WithMany()
                        .HasForeignKey("LicenseImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.TownItem", "Town")
                        .WithMany("Drivers")
                        .HasForeignKey("TownId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.GroupItem", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ApplicationFile")
                        .WithMany()
                        .HasForeignKey("ApplicationFileId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "DriverGuranteeFile")
                        .WithMany()
                        .HasForeignKey("DriverGuranteeFileId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage1")
                        .WithMany()
                        .HasForeignKey("ExtraImage1Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage2")
                        .WithMany()
                        .HasForeignKey("ExtraImage2Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage3")
                        .WithMany()
                        .HasForeignKey("ExtraImage3Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "GroupGuranteeFile")
                        .WithMany()
                        .HasForeignKey("GroupGuranteeFileId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "LicenseImage")
                        .WithMany()
                        .HasForeignKey("LicenseImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "MainImage")
                        .WithMany()
                        .HasForeignKey("MainImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "RuleFile")
                        .WithMany()
                        .HasForeignKey("RuleFileId");

                    b.HasOne("Socona.ImVehicle.Core.Data.TownItem", "Town")
                        .WithMany("Groups")
                        .HasForeignKey("TownId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.NewsItem", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ImageFile")
                        .WithMany()
                        .HasForeignKey("ImageFileId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.SecurityPerson", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.GroupItem", "Group")
                        .WithMany("SecurityPersons")
                        .HasForeignKey("GroupId");

                    b.HasOne("Socona.ImVehicle.Core.Data.TownItem", "Town")
                        .WithMany()
                        .HasForeignKey("TownId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.TownItem", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.DistrictItem", "District")
                        .WithMany("Towns")
                        .HasForeignKey("DirstrictId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.UserFileItem", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.GroupItem", "Group")
                        .WithMany("UserFiles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Socona.ImVehicle.Core.Data.TownItem", "Town")
                        .WithMany()
                        .HasForeignKey("TownId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleItem", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.DriverItem", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage1")
                        .WithMany()
                        .HasForeignKey("ExtraImage1Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage2")
                        .WithMany()
                        .HasForeignKey("ExtraImage2Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "ExtraImage3")
                        .WithMany()
                        .HasForeignKey("ExtraImage3Id");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "FrontImage")
                        .WithMany()
                        .HasForeignKey("FrontImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "GpsImage")
                        .WithMany()
                        .HasForeignKey("GpsImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.GroupItem", "Group")
                        .WithMany("Vehicles")
                        .HasForeignKey("GroupId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "LicenseImage")
                        .WithMany()
                        .HasForeignKey("LicenseImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.UserFileItem", "RearImage")
                        .WithMany()
                        .HasForeignKey("RearImageId");

                    b.HasOne("Socona.ImVehicle.Core.Data.TownItem", "Town")
                        .WithMany("Vehicles")
                        .HasForeignKey("TownId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleRole", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.VehicleRole", "BaseRole")
                        .WithMany()
                        .HasForeignKey("BaseRoleId");
                });

            modelBuilder.Entity("Socona.ImVehicle.Core.Data.VehicleUser", b =>
                {
                    b.HasOne("Socona.ImVehicle.Core.Data.DistrictItem", "District")
                        .WithMany("Users")
                        .HasForeignKey("DistrictId");

                    b.HasOne("Socona.ImVehicle.Core.Data.GroupItem", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId");

                    b.HasOne("Socona.ImVehicle.Core.Data.TownItem", "Town")
                        .WithMany("Users")
                        .HasForeignKey("TownId");
                });
#pragma warning restore 612, 618
        }
    }
}
